const tap = require('tap')
const ct = require('./App')
const { existsSync } = require('fs')
const tstpkg = require('./test-dir/package.json')

tap.throws(() => ct(), new Error('Please enter a valid path'))
tap.throws(() => ct(0), new Error('Please enter a valid path'))
tap.throws(() => ct(''), new Error('Please enter a valid path'))
// tap.throws(() => ct(dtd,'./'), new Error('Please enter a valid path'))
tap.throws(() => ct('./notfound'), new Error('Please enter a valid path'))
tap.throws(() => ct('./test.js'), new Error('Please enter a valid path'))
// ct('./test-dir/')
tap.equal(typeof ct('./test-dir/'), 'string')
tap.equal(tstpkg.scripts.test, 'standard && node test.js | tap-spec')
tap.equal(existsSync('./test-dir/test.js'), true)
